---
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/Tracker
    username: root
    password: tracker
    platform: mysql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: tracker_db_creation.sql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
