INSERT INTO Tag VALUES (7,'Hibernate');
INSERT INTO Tag VALUES	(1,'Java');
INSERT INTO Tag VALUES	(6,'JPA');
INSERT INTO Tag VALUES	(2,'Spring');
INSERT INTO Tag VALUES	(3,'Spring Boot');
INSERT INTO Tag VALUES	(4,'Spring MVC');

INSERT INTO Course VALUES	(1,'John Thompson','2017-08-01','Java Spring Boot','Spring Framework 5: Beginner to Guru','https://www.udemy.com/spring-framework-5-beginner-to-guru/');
INSERT INTO Course VALUES	(2,'Esteban Herrera','2018-04-01','Spring WebFlux','Spring WebFlux: Getting Started','https://app.pluralsight.com/library/courses/getting-started-spring-webflux');
INSERT INTO Course VALUES	(3,'Bryan Hansen','2013-04-10','Spring JDBC with JPA/Hibernate','Spring with JPA and Hibernate','https://app.pluralsight.com/library/courses/spring-jpa-hibernate/');

INSERT INTO Course_tags VALUES (1,1);
INSERT INTO Course_tags VALUES (2,1);
INSERT INTO Course_tags VALUES (3,1);
INSERT INTO Course_tags VALUES (1,2);
INSERT INTO Course_tags VALUES (2,2);
INSERT INTO Course_tags VALUES (3,2);
INSERT INTO Course_tags VALUES (1,3);
INSERT INTO Course_tags VALUES (1,4);
INSERT INTO Course_tags VALUES (3,6);
INSERT INTO Course_tags VALUES (3,7);

INSERT INTO My_Course VALUES (1,'0','old course, 5h long',3);
INSERT INTO My_Course VALUES (2,'0','All MVC content uses Spring Boot, intro''s into: Docker & MongoDB are nice.',1);


INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-security-thymeleafSpring','Security with Thymeleaf | Baeldung');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-security-5-password-storage','New Password Storage In Spring Security 5');
INSERT INTO Course (url,title) VALUES ('https://vladmihalcea.com/a-beginners-guide-to-jpa-and-hibernate-cascade-types/','A beginner’s guide to JPA and Hibernate Cascade Types');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/30118683/how-to-log-sql-statements-in-spring-boot','how to log sql statements in spring-boot');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/15972549/jpa-collection-has-unwanted-unique-constraint-in-mapping-table','JPA Collection has unwanted unique constraint in mapping table');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/convert-map-values-to-array-list-set','Convert a Map to an Array, List or Set in Java | Baeldung');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/37715276/how-do-i-populate-a-drop-down-with-a-list-using-thymeleaf-and-spring','How do I populate a drop down with a list using thymeleaf and spring');
INSERT INTO Course (url,title) VALUES ('https://teamtreehouse.com/community/how-to-add-an-object-and-then-another-object-as-an-attribute-to-the-first-object-in-a-thymeleaf-template','How to add an object and then another object as an attribute to the first object in a Thymeleaf template?');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/22794057/thymeleaf-send-parameter-from-html-to-controller','Thymeleaf send parameter from html to controller');
INSERT INTO Course (url,title) VALUES ('https://www.devglan.com/spring-boot/spring-boot-hibernate-5-exampleSpring','Boot + Hibernate 5 + Mysql Example');
INSERT INTO Course (url,title) VALUES ('https://www.thoughts-on-java.org/how-to-join-unrelated-entities/','How to join unrelated entities with JPA and Hibernate');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/12907921/entitymanager-query-by-joincolumn','EntityManager query by joinColumn');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/java-spliterator','Introduction to Spliterator in Java');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/24301114/passing-model-attribute-during-redirect-in-spring-mvc-and-avoiding-the-same-in-u/24302616','Passing model attribute during redirect in spring MVC and avoiding the same in URL');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-profiles','Spring Profiles');
INSERT INTO Course (url,title) VALUES ('https://www.mkyong.com/spring-boot/spring-boot-profiles-example/','Spring Boot Profiles example');
INSERT INTO Course (url,title) VALUES ('https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html','Spring boot 74. Properties and Configuration');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/38040572/spring-boot-loading-initial-data','Spring Boot - Loading Initial Data');
INSERT INTO Course (url,title) VALUES ('https://www.mkyong.com/spring-mvc/spring-mvc-form-check-if-a-field-has-an-error/','Spring MVC Form – Check if a field has an error');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git','How do I commit case-sensitive only filename changes in Git?');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git/16071375','Changing capitalization of filenames in Git');
INSERT INTO Course (url,title) VALUES ('https://www.garron.me/en/bits/git-ignorecase-rename-lowercase-uppercase.html','Git on Mac ignoring rename uppercase to lowercase');
INSERT INTO Course (url,title) VALUES ('https://examples.javacodegeeks.com/enterprise-java/spring/mvc/spring-mvc-using-log4j-example/','Spring MVC using Log4j Example');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/logging-with-slf4j','Logging With SLF4J');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/slf4j-with-log4j2-logback','Introduction to SLF4J');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/configuring-logback-with-spring-boot','Configuring Logback With Spring Boot');
INSERT INTO Course (url,title) VALUES ('https://www.callicoder.com/spring-boot-log4j-2-example/','How to use Log4j 2 with Spring Boot');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/log4j-2-configuration-using-yaml/','LOG4J 2 CONFIGURATION: USING YAML');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/introducing-log4j-enterprise-class-logging/','INTRODUCING LOG4J 2 – ENTERPRISE CLASS LOGGING');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/log4j-2-configuration','Log4j 2 Configuration Using YAML');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/spring-framework-annotations/','SPRING FRAMEWORK ANNOTATIONS');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-mvc-session-attributes','Session Attributes in Spring MVC');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/10401402/how-to-share-sessionattributes-between-controllers-in-spring-mvc','How to share SessionAttributes between Controllers in Spring MVC?');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/gs/validating-form-input/','GETTING STARTED Validating Form Input');
INSERT INTO Course (url,title) VALUES ('https://education.github.com/git-cheat-sheet-education.pdf','GITHUB - GIT CHEAT SHEET');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/tutorials/bookmarks/','Building REST services with Spring');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/29602386/how-does-the-fetchmode-work-in-spring-data-jpa','How does the FetchMode work in Spring Data JPA');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/global-exception-handling-with-controlleradvice','Global Exception Handling With @ControllerAdvice');
INSERT INTO Course (url,title) VALUES ('https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc','Exception Handling in Spring MVC');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/14014086/what-is-difference-between-crudrepository-and-jparepository-interfaces-in-spring','What is difference between CrudRepository and JpaRepository interfaces in Spring Data JPA?');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/34858989/wrong-date-format-when-submit-spring-form','Wrong date format when submit Spring form');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/dates-in-thymeleaf','How to Work with Dates in Thymeleaf');
INSERT INTO Course (url,title) VALUES ('https://ankeetmaini.wordpress.com/2012/01/24/binding-date-in-spring/','BINDING DATE IN SPRING');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/25333711/what-is-the-use-of-the-temporal-annotation-in-hibernate','What is the use of the @Temporal annotation in Hibernate?');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/hibernate-date-time','Hibernate – Mapping Date and Time');
INSERT INTO Course (url,title) VALUES ('https://www.thoughts-on-java.org/persist-localdate-localdatetime-jpa/','How to persist LocalDate and LocalDateTime with JPA');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/43044121/attributeconverter-date-string','AttributeConverter Date String');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/exploring-spring-controller','Exploring Spring Controller with JSTL View');
INSERT INTO Course (url,title) VALUES ('https://docs.spring.io/spring/docs/2.5.x/reference/validation.html#beans-beans-conversion-customeditor-registration','5.4.2.1. Registering additional custom PropertyEditors');
INSERT INTO Course (url,title) VALUES ('https://www.callicoder.com/spring-boot-rest-api-tutorial-with-mysql-jpa-hibernate/','Spring Boot, MySQL, JPA, Hibernate Restful CRUD API Tutorial');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/hibernate-save-persist-update-merge-saveorupdate','Hibernate: save, persist, update, merge, saveOrUpdate');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/hibernate-one-to-many','Hibernate One to Many Annotation Tutorial');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/438146/hibernate-hbm2ddl-auto-possible-values-and-what-they-do','Hibernate hbm2ddl.auto possible values and what they do?');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/gs/accessing-data-jpa/','Accessing Data with JPA');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/32873844/how-to-automatic-create-table-in-jpa-persistence-xml-file','how to automatic create table in jpa persistence xml file?');
INSERT INTO Course (url,title) VALUES ('https://gist.github.com/hofmannsven/9164408','My simply MySQL Command Line Cheatsheet');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-boot-command-line-arguments','Command-Line Arguments in Spring Boot');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/23316843/get-command-line-arguments-from-spring-bootrun','Get command-line arguments from spring-boot:run');
INSERT INTO Course (url,title) VALUES ('https://spring.io/understanding/HATEOAS','Understanding HATEOAS');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/48900892/how-to-enable-all-endpoints-in-actuator-spring-boot-2-0-0-rc1/48901161#48901161','How to enable all endpoints in actuator (Spring Boot 2.0.0 RC1)');
INSERT INTO Course (url,title) VALUES ('https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints-exposing-endpoints','50.2 Exposing Endpoints');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/gs/actuator-service/','Building a RESTful Web Service with Spring Boot Actuator');
INSERT INTO Course (url,title) VALUES ('https://github.com/spring-cloud/spring-cloud-config/issues/887','Document "spring.cloud.config.server.encrypt.enabled: false" should go in bootstrap.{properties|yml}');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/49281778/spring-config-server-encrypt-forbidden','spring config server encrypt forbidden');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/gs/securing-web/','Securing a Web Application');
INSERT INTO Course (url,title) VALUES ('https://therealdanvega.com/blog/2018/03/01/what-is-new-spring-boot-2','WHAT’S NEW IN SPRING BOOT 2');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/23894010/spring-boot-security-disable-security/34150562','Spring boot Security Disable security');
INSERT INTO Course (url,title) VALUES ('https://medium.com/nycdev/java-build-a-tomcat-web-app-with-maven-and-spring-fbc823fa9a37','Java: Create a Spring MVC App with Tomcat and Maven');
INSERT INTO Course (url,title) VALUES ('https://www.boraji.com/spring-mvc-5-spring-security-5-hibernate-5-example','Spring MVC 5 + Spring Security 5 + Hibernate 5 example');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java','9 Best Practices to Handle Exceptions in Java');
INSERT INTO Course (url,title) VALUES ('https://therealdanvega.teachable.com/p/jhipster-free-course','Angular 4 Java Developers - Learn how to build Spring Boot & Angular apps using JHipster');
INSERT INTO Course (url,title) VALUES ('https://www.codecram.com/','CodeCram');
INSERT INTO Course (url,title) VALUES ('https://objectpartners.com/2015/01/13/reset-your-h2-database-for-a-clean-state-between-functional-tests/','Reset Your H2 Database For A Clean State Between Functional Tests');
INSERT INTO Course (url,title) VALUES ('https://brightinventions.pl/blog/clear-database-in-spring-boot-tests/','How to clear database in Spring Boot tests?');
INSERT INTO Course (url,title) VALUES ('https://medium.com/@dSebastien/cleaning-up-database-tables-after-each-integration-test-method-with-spring-boot-2-and-kotlin-7279abcdd5cc','Cleaning up database tables after each integration test method with Spring Boot 2 and Kotlin');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/20295578/difference-between-before-beforeclass-beforeeach-and-beforeall','Difference between @Before, @BeforeClass, @BeforeEach and @BeforeAll');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-boot-data-sql-and-schema-sql','Quick Guide on Loading Initial Data with Spring Boot');
INSERT INTO Course (url,title) VALUES ('http://www.springboottutorial.com/spring-boot-and-h2-in-memory-database','Spring Boot and H2 in memory database - Why, What and How?');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-data-jpa-multiple-databases','Spring JPA – Multiple Databases');
INSERT INTO Course (url,title) VALUES ('https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-two-datasources','80.2 Configure Two DataSources');
INSERT INTO Course (url,title) VALUES ('https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html','81. Database Initialization');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/39280340/spring-boot-run-sql-scripts-and-get-data-on-application-startup','Spring boot. Run SQL scripts and get data on application startup');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-testing-separate-data-source','Configuring Separate Spring DataSource for Tests');
INSERT INTO Course (url,title) VALUES ('https://www.programcreek.com/java-api-examples/?class=org.springframework.web.servlet.mvc.support.RedirectAttributes&method=addFlashAttribute','Java Code Examples for org.springframework.web.servlet.mvc.support.RedirectAttributes.addFlashAttribute()');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/spring-mvc-flash-attributes','Spring MVC - Flash Attributes');
INSERT INTO Course (url,title) VALUES ('https://thepracticaldeveloper.com/2017/07/31/guide-spring-boot-controller-tests/#Strategy_1_MockMVC_in_Standalone_Mode','Unit and Integration Tests for RestControllers in Spring Boot');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/junit-testing-spring-mvc-0','JUnit testing of Spring MVC application: Testing the Service Layer');
INSERT INTO Course (url,title) VALUES ('https://memorynotfound.com/unit-test-spring-mvc-rest-service-junit-mockito/','Unit Test Spring MVC Rest Service: MockMVC, JUnit, Mockito');
INSERT INTO Course (url,title) VALUES ('http://www.mkyong.com/spring-mvc/spring-mvc-handler-interceptors-example/','Spring MVC handler interceptors example');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/31082981/spring-boot-adding-http-request-interceptors','spring boot adding http request interceptors');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/11139571/scope-of-a-spring-controller-and-its-instance-variables','Scope of a Spring-Controller and its instance-variables');
INSERT INTO Course (url,title) VALUES ('https://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/session-attribute.html','Spring MVC - Accessing pre-existing session attributes using @SessionAttribute');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-cloud-angular','Spring Cloud – Adding Angular 4');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/hibernate-show-sql/','Hibernate Show SQL - Spring Framework Guru');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/unit-and-integration-tests-in-spring-boot','Unit and Integration Tests in Spring Boot - DZone Integration');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-boot-testing','Testing in Spring Boot | Baeldung');
INSERT INTO Course (url,title) VALUES ('https://myshittycode.com/2014/01/16/mockmvc-mockito-epic-tests/','MockMvc + Mockito = Epic Tests');
INSERT INTO Course (url,title) VALUES ('https://www.foreach.be/blog/java-8-date-and-time','Java 8 Date and Time');
INSERT INTO Course (url,title) VALUES ('https://spring.io/guides/gs/messaging-rabbitmq/','Messaging with RabbitMQ');
INSERT INTO Course (url,title) VALUES ('https://www.nginx.com/blog/introduction-to-microservices/','Introduction to Microservices');
INSERT INTO Course (url,title) VALUES ('https://www.javacodegeeks.com/2014/06/microservice-architecture-a-quick-guide.html','Microservice Architecture – A Quick Guide');
INSERT INTO Course (url,title) VALUES ('https://www.codementor.io/community/topic/microservices','Microservices Tutorials and Insights');
INSERT INTO Course (url,title) VALUES ('https://www.javaworld.com/article/2952103/enterprise-java/build-an-api-for-microservices-in-5-minutes.html','Build an API for microservices in 5 minutes');
INSERT INTO Course (url,title) VALUES ('https://auth0.com/blog/an-introduction-to-microservices-part-1/','An Introduction to Microservices, Part 1');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/using-circleci-to-build-spring-boot-microservices/','USING CIRCLECI TO BUILD SPRING BOOT MICROSERVICES');
INSERT INTO Course (url,title) VALUES ('https://refactoring.guru/design-patterns/factory-method/java/example','Java: Factory Method');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/java-the-factory-pattern','Java: The Factory Method Pattern');
INSERT INTO Course (url,title) VALUES ('https://www.javaworld.com/article/2077386/learn-java/factory-methods.html','Factory methods - How do you employ factory methods to your best advantage?');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-controllers','Quick Guide to Spring Controllers');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/gang-of-four-design-patterns/#comment-2412','Gang of Four Design Patterns');
INSERT INTO Course (url,title) VALUES ('https://medium.com/@krzychukosobudzki/repository-design-pattern-bc490b256006','Repository Design Pattern');
INSERT INTO Course (url,title) VALUES ('https://content.pivotal.io/springone-platform-2017','SpringOne Platform 2017');
INSERT INTO Course (url,title) VALUES ('http://websystique.com/springmvc/spring-4-mvc-angularjs-crud-application-using-ngresource/','Spring 4 MVC+AngularJS CRUD Application using ngResource');
INSERT INTO Course (url,title) VALUES ('http://www.nakov.com/blog/2016/08/05/creating-a-blog-system-with-spring-mvc-thymeleaf-jpa-and-mysql/','Creating a Blog System with Spring MVC, Thymeleaf, JPA and MySQL');
INSERT INTO Course (url,title) VALUES ('http://coderscampus.com/ultimate-guide-hosting-java-web-app-amazon-web-services-aws/','THE ULTIMATE GUIDE TO HOSTING A JAVA WEB APP WITH AMAZON WEB SERVICES (AWS)');
INSERT INTO Course (url,title) VALUES ('https://springframework.guru/using-jaxb-for-xml-with-java/','USING JAXB FOR XML WITH JAVA');
INSERT INTO Course (url,title) VALUES ('https://www.javacodegeeks.com/2013/07/unit-testing-of-spring-mvc-controllers-normal-controllers.html','Unit Testing of Spring MVC Controllers: “Normal” Controllers');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/how-to-mock-spring-bean-version-2','How to Mock, Spy, and Fake Spring Beans');
INSERT INTO Course (url,title) VALUES ('http://www.springboottutorial.com/unit-testing-for-spring-boot-rest-services','Unit Testing Rest Services with Spring Boot and JUnit');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/34649595/spring-test-mvc-how-to-use-object-as-request-parameters','Spring Test MVC : How to use object as Request Parameters');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-mvc-custom-validator','Spring MVC Custom Validation');
INSERT INTO Course (url,title) VALUES ('https://medium.com/@konstantinnalum/input-validation-and-unit-testing-of-a-rest-controller-in-spring-boot-304b82ca7526','Input validation and unit testing of a rest controller in spring boot');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/13745848/how-to-test-valid','How to test @Valid');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/mockito-mock-vs-spy-in-spring-boot-tests','Mockito Mock vs. Spy in Spring Boot Tests - DZone Java');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/47503849/spring-boot-logger-logs-nothing','Spring boot logger logs nothing');
INSERT INTO Course (url,title) VALUES ('http://javainsimpleway.com/spring-mvc-redirecting-model-attributes-from-one-controller-to-other-controller/','Spring MVC – Redirecting model attributes from one controller to other controller');
INSERT INTO Course (url,title) VALUES ('http://forum.spring.io/forum/spring-projects/web/41668-transfer-of-data-from-one-controller-to-another','TRANSFER OF DATA FROM ONE CONTROLLER TO ANOTHER');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/a-guide-to-mocking-with-mockito','A Guide to Mocking With Mockito');
INSERT INTO Course (url,title) VALUES ('https://www.dontpanicblog.co.uk/2013/11/14/mockmvc-to-test-spring-mvc-form-validation/','MockMVC to test Spring MVC form validation');
INSERT INTO Course (url,title) VALUES ('https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#local-variables','thymeleaf 9 Local Variables');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/25133807/thymeleaf-how-to-use-conditionals-to-dynamically-add-remove-a-css-class','Thymeleaf: how to use conditionals to dynamically add/remove a CSS class');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-thymeleaf-fragments','Working with Fragments in Thymeleaf');
INSERT INTO Course (url,title) VALUES ('https://dzone.com/articles/using-http-session-spring','Using Http Session With Spring Based Web Applications');
INSERT INTO Course (url,title) VALUES ('http://www.javainterviewpoint.com/spring-mvc-multiple-submit-buttons-in-a-single-form/','Spring MVC Multiple submit buttons in a single form');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/8954426/spring-mvc-multiple-submit-button-to-a-form','Spring MVC - Multiple submit button to a Form');
INSERT INTO Course (url,title) VALUES ('https://stackoverflow.com/questions/16514501/spring-3-form-with-2-buttons-sending-2-parameters-to-controller-method','Spring 3 — form with 2 buttons, sending 2 parameters to controller method');
INSERT INTO Course (url,title) VALUES ('http://www.baeldung.com/spring-dataIntegrityviolationexception','Spring DataIntegrityViolationException');
INSERT INTO Course (url,title) VALUES ('https://rollbar.com/blog/spring-mvc-exception-handling/','Spring MVC Exception Handling and Monitoring');
INSERT INTO Course (url,title) VALUES ('http://forum.spring.io/forum/spring-projects/web/30590-binding-to-a-list-string','Binding to a List<String>');
